CREATE TABLE cdm_applications
(
  id                        number(28) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1, -- id assigned from a sequence (primary key for this table)
  application_name          nvarchar2(256) NOT NULL, 
  application_id            nvarchar2(256) NOT NULL,  -- Fully qualified application name (com.example.ProjectX)
  deployment_id             number(28) NOT NULL, -- Unique number for each deployed version, used in undeploy/status calls
  major_version             number(5) NOT NULL, -- Columns types for the 4 version number parts mirror those used by DEM's schema
  minor_version             number(5) NOT NULL,
  micro_version             number(5) NOT NULL,
  qualifier                 nvarchar2(36)	NOT NULL,
  deployment_timestamp      timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT cdm_applications_pk PRIMARY KEY (id)
);

CREATE TABLE cdm_datamodels
(
  id                        number(28) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1, -- id assigned from a sequence (primary key for this table)
  application_id			number(28) NOT NULL, -- id of application (numeric, assigned from sequence) in cdm_applications
  major_version             number(5) NOT NULL, -- e.g. 1 (duplicated from cdm_applications to allow cdm_datamodels_unq) 
  namespace                 nvarchar2(256) NOT NULL, -- e.g. "com.example.carmodel"
  model                     nclob NOT NULL,
  script                    nclob, -- TODO make this NOT NULL once everything is integrated
  CONSTRAINT cdm_datamodels_pk PRIMARY KEY (id),
  CONSTRAINT cdm_datamodels_fk1 FOREIGN KEY (application_id)
    REFERENCES cdm_applications (id) ON DELETE CASCADE,
  CONSTRAINT cdm_datamodels_unq UNIQUE (namespace, major_version)    
);

CREATE TABLE cdm_types
(
	id                     number(28) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1, -- id assigned from a sequence (primary key for this table)
	datamodel_id           number(28) NOT NULL, -- id of datamodel in cdm_datamodels
	name                   nvarchar2(256) NOT NULL, -- name of type (e.g. 'Address')
	is_case                number(1) NOT NULL, -- 1 if case, 0 if not
  CONSTRAINT cdm_types_pk PRIMARY KEY (id),
  CONSTRAINT cdm_types_fk1 FOREIGN KEY (datamodel_id)
    REFERENCES cdm_datamodels (id) ON DELETE CASCADE
);

CREATE TABLE cdm_states -- TODO Does order of states need to be maintained? If so, need an idx column.
(
    id                     number(28) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1, -- id assigned from a sequence (primary key for this table)
    type_id                number(28) NOT NULL, -- id of type in cdm_types
    value                  nvarchar2(256) NOT NULL,
    label                  nvarchar2(256) NOT NULL, -- TODO don't think label length is validated
    is_terminal            number(1) NOT NULL, -- 1 if case, 0 if not
  CONSTRAINT cdm_states_pk PRIMARY KEY (id),
  CONSTRAINT cdm_states_fk1 FOREIGN KEY (type_id)
    REFERENCES cdm_types (id) ON DELETE CASCADE
);

CREATE TABLE cdm_type_indexes
(
    type_id                number(28) NOT NULL, -- id of type in cdm_types
	name                   nvarchar2(256) NOT NULL, -- name of index (e.g. 'i_cdm_ordermodel_Address_postcode')
	attribute_name         nvarchar2(256) NOT NULL, -- name of attribute (e.g. 'postcode')
  CONSTRAINT cdm_type_indexes_fk1 FOREIGN KEY (type_id)
    REFERENCES cdm_types (id) -- no 'on delete cascade', as we want to make sure we explicitly remove indexes
);

CREATE TABLE cdm_datamodel_deps
(
  datamodel_id_from			number(28) NOT NULL, -- id of datamodel in cdm_datamodels
  datamodel_id_to			number(28) NOT NULL, -- id of datamodel on which the first depends
  CONSTRAINT cdm_datamodel_deps_pk PRIMARY KEY (datamodel_id_from, datamodel_id_to),
  CONSTRAINT cdm_datamodel_deps_fk1 FOREIGN KEY (datamodel_id_from) 
    REFERENCES cdm_datamodels (id) ON DELETE CASCADE,
  CONSTRAINT cdm_datamodel_deps_fk2 FOREIGN KEY (datamodel_id_to) 
    REFERENCES cdm_datamodels (id) -- no 'on delete cascade' (no desire to allow the 'to' model to be deleted while the 'from' depends on it)
);

CREATE TABLE cdm_identifier_infos
(
  type_id                   number(28) NOT NULL, -- id of type in cdm_types
  prefix                    nvarchar2(32), 
  suffix                    nvarchar2(32), 
  min_num_length            number(2),
  next_num                  number(15) NOT NULL,
  CONSTRAINT cdm_identifier_infos_pk PRIMARY KEY (type_id),
  CONSTRAINT cdm_identifier_infos_fk_type_id FOREIGN KEY (type_id)
    REFERENCES cdm_types (id) ON DELETE CASCADE
);

CREATE TABLE cdm_links
(
  id                        number(28) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1, -- id assigned from a sequence (primary key for this table)
  end1_owner_id             number(28) NOT NULL, -- id of owner type in cdm_types
  end1_name                 nvarchar2(256) NOT NULL,  -- name of end
  end1_is_array             number(1) NOT NULL,     -- 1 if array
  end2_owner_id             number(28) NOT NULL, 
  end2_name                 nvarchar2(256) NOT NULL,
  end2_is_array             number(1) NOT NULL,		-- 1 if array
  CONSTRAINT cdm_links_pk PRIMARY KEY (id),
  CONSTRAINT cdm_links_unq UNIQUE (end1_owner_id, end1_name, end2_owner_id, end2_name), 
  CONSTRAINT cdm_links_fk_end1_owner_id FOREIGN KEY (end1_owner_id)
    REFERENCES cdm_types (id) ON DELETE CASCADE,
  CONSTRAINT cdm_links_fk_end2_owner_id FOREIGN KEY (end2_owner_id)
    REFERENCES cdm_types (id) ON DELETE CASCADE
);

CREATE TABLE cdm_cases_int
(
  id                        number(28) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1, -- (like 'bds_id' in BDS)
  version                   number(15) NOT NULL, -- (like 'bds_version' in BDS)
  type_id                   number(28) NOT NULL, -- id of type in cdm_types
  casedata                  nclob NOT NULL,
  cid                       nvarchar2(400) NOT NULL, 
  state_id                  number(28) NOT NULL, -- id of state in cdm_states
  created_by                nvarchar2(36) NOT NULL, -- 36 char GUID (obtained from RequestContext.getCurrentUser().getGuid())
  creation_timestamp        timestamp with time zone 	DEFAULT CURRENT_TIMESTAMP NOT NULL,
  modified_by               nvarchar2(36) NOT NULL, -- 36 char GUID (obtained from RequestContext.getCurrentUser().getGuid())
  modification_timestamp    timestamp with time zone 	DEFAULT CURRENT_TIMESTAMP NOT NULL,
  marked_for_purge          number(1) DEFAULT 0,
  CONSTRAINT cdm_cases_int_pk PRIMARY KEY (id),
  CONSTRAINT cdm_cases_int_unq UNIQUE (type_id, cid), -- enforce uniqueness of CID for a given type
  CONSTRAINT cdm_cases_int_fk_type_id FOREIGN KEY (type_id)
	REFERENCES cdm_types (id),
  CONSTRAINT cdm_cases_int_fk_state_id FOREIGN KEY (state_id)
    REFERENCES cdm_states (id) 
);

CREATE TABLE cdm_case_links
(
  link_id                   number(28) NOT NULL, -- Foreign key to link definition in cdm_links table
  end1_id                   number(28) NOT NULL, -- id of first case object
  end2_id                   number(28) NOT NULL, -- id of second case object
  CONSTRAINT cdm_case_links_pk PRIMARY KEY (link_id, end1_id, end2_id),
  CONSTRAINT cdm_case_links_fk_link_id FOREIGN KEY (link_id)
    REFERENCES cdm_links (id) ON DELETE CASCADE,
  CONSTRAINT cdm_case_links_fk_end1_id FOREIGN KEY (end1_id)
    REFERENCES cdm_cases_int (id) ON DELETE CASCADE, -- TODO remove cascade once delete (multiple) cases made to remove links
  CONSTRAINT cdm_case_links_fk_end2_id FOREIGN KEY (end2_id)
    REFERENCES cdm_cases_int (id) ON DELETE CASCADE  -- TODO remove cascade once delete (multiple) cases made to remove links
);


CREATE TABLE cdm_properties
(
	name		nvarchar2(256) NOT NULL,
	value		nvarchar2(256) NOT NULL,
	CONSTRAINT cdm_properties_pk PRIMARY KEY (name)
);

CREATE TABLE cdm_job_queue
(
	message_id 	number(28) GENERATED BY DEFAULT ON NULL AS IDENTITY,
	correlation_id 	nvarchar2(128) NULL,
	priority 	number(5) NOT NULL,
	delay 		timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	payload 	blob NOT NULL,
	enq_time 	timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	retry_count number(5) DEFAULT -1,
	CONSTRAINT cdm_job_queue_pk PRIMARY KEY (message_id)
);

CREATE INDEX ix_cdm_job_queue_correlation_id ON cdm_job_queue (correlation_id);
CREATE INDEX ix_cdm_job_queue_delay ON cdm_job_queue (delay);
CREATE INDEX ix_cdm_job_queue_priority_enq_time ON cdm_job_queue (priority, enq_time);

/*
 * Object:  View cdm_cases
 */
CREATE OR REPLACE VIEW cdm_cases 
AS
 SELECT c.cid AS case_identifier,
    c.id || '-' || d.namespace || '.' || t.name || '-' || d.major_version || '-' || c.version AS casereference,
    c.id || '-' || d.namespace || '.' || t.name || '-' || d.major_version AS unversioned_casereference,
    d.namespace || '.' || t.name AS type,
    c.version,
    s.value AS state,
    c.casedata,
    CASE 
      WHEN s.is_terminal = 0 THEN 1
      ELSE 0
    END AS is_active,
    c.creation_timestamp AS creation_timestamp,
    c.modification_timestamp AS modification_timestamp,
    CASE 
      WHEN s.is_terminal = 1 THEN c.modification_timestamp - c.creation_timestamp
      ELSE c.modification_timestamp - c.modification_timestamp 
    END AS completed_case_duration,
    a.application_name,
    a.application_id,
    a.major_version || '.' || a.minor_version || '.' || a.micro_version || '.' || a.qualifier AS application_version
   FROM cdm_cases_int c
     JOIN cdm_types t ON c.type_id = t.id
     JOIN cdm_datamodels d ON t.datamodel_id = d.id
     JOIN cdm_states s ON c.state_id = s.id
     JOIN cdm_applications a ON d.application_id = a.id
   WHERE c.marked_for_purge = 0 
   ORDER BY c.modification_timestamp desc;   
   
 